
import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ScrollText, ShieldCheck, X } from 'lucide-react';

export default function TermsModal({ isOpen, onClose }) {
  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6 lg:p-8">
        {/* Backdrop */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          className="absolute inset-0 bg-gray-900/60 backdrop-blur-md"
        />

        {/* Modal Card */}
        <motion.div
          initial={{ scale: 0.9, opacity: 0, y: 20 }}
          animate={{ scale: 1, opacity: 1, y: 0 }}
          exit={{ scale: 0.9, opacity: 0, y: 20 }}
          className="relative w-full max-w-4xl max-h-[90vh] bg-white rounded-[2.5rem] shadow-2xl overflow-hidden flex flex-col border border-gray-100"
        >
          {/* Header */}
          <div className="p-8 border-b border-gray-100 flex items-center justify-between sticky top-0 bg-white z-10">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-gray-50 rounded-xl text-gray-900">
                <ScrollText size={20} />
              </div>
              <div>
                <h2 className="text-xl font-black text-gray-900 tracking-tight">Terms & Conditions</h2>
                <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Last Updated: April 2026</p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-3 hover:bg-gray-100 rounded-2xl transition-all text-gray-400 hover:text-gray-900"
            >
              <X size={20} />
            </button>
          </div>

          {/* Scrollable Content */}
          <div className="p-8 md:p-12 overflow-y-auto custom-scrollbar">
            <div className="grid md:grid-cols-2 gap-12">
              <div className="space-y-4">
                <h3 className="text-sm font-black uppercase tracking-widest text-gray-900 flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-gray-900" />
                  1. Platform Usage
                </h3>
                <p className="text-gray-500 font-medium text-sm leading-relaxed">
                  VIRQA is intended for professional appraisal and practice. Users must engage with the system in a manner that respects intellectual property and professional ethics.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-sm font-black uppercase tracking-widest text-gray-900 flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-gray-900" />
                  2. Data Attribution
                </h3>
                <p className="text-gray-500 font-medium text-sm leading-relaxed">
                  Evaluations generated by VIRQA are based on semantic analysis of user input. These reports remain the property of the account holder but are subject to our internal data security protocols.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-sm font-black uppercase tracking-widest text-gray-900 flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-gray-900" />
                  3. Inference Accuracy
                </h3>
                <p className="text-gray-500 font-medium text-sm leading-relaxed">
                  While our AI utilizes state-of-the-art models, feedback should be used as a high-fidelity guide. Technical benchmarks are cross-referenced with public industry standards.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-sm font-black uppercase tracking-widest text-gray-900 flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-gray-900" />
                  4. Privacy Protocol
                </h3>
                <p className="text-gray-500 font-medium text-sm leading-relaxed">
                  We adhere to strict data compartmentalization. User sessions are transcribed and analyzed for the express purpose of generating professional appraisal reports.
                </p>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="p-8 border-t border-gray-100 bg-gray-50 flex items-center justify-between">
            <div className="flex items-center gap-2 text-emerald-600">
              <ShieldCheck size={16} />
              <span className="text-[10px] font-bold uppercase tracking-widest text-emerald-700">Enterprise Compliant</span>
            </div>
            <button
              onClick={onClose}
              className="px-8 py-3 bg-gray-900 text-white rounded-xl font-bold text-sm hover:scale-105 active:scale-95 transition-all"
            >
              I Understand
            </button>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
