import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useMutation } from '@tanstack/react-query';
import { FiLock, FiCheck } from 'react-icons/fi';
import { motion } from 'framer-motion';
import { toast } from 'react-toastify';
import Logo from '../../components/common/Logo.jsx';
import { api } from '../../config/api.js';

const ForcePasswordChange = () => {
    const [password, setPassword] = useState('');
    const [confirmPassword, setConfirmPassword] = useState('');
    const navigate = useNavigate();

    const changePasswordMutation = useMutation({
        mutationFn: async (newPassword) => {
            const res = await api.patch('/user/change-password', { newPassword });
            return res.data;
        },
        onSuccess: () => {
            toast.success('Password updated successfully! Welcome to VIRQA.');
            // Default routing after setting password for institute
            navigate('/api/v1/employee/dashboard');
        },
        onError: (error) => {
            toast.error(error.response?.data?.message || 'Failed to update password');
        }
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        if (password !== confirmPassword) {
            toast.error("Passwords do not match");
            return;
        }
        if (password.length < 6) {
            toast.error("Password must be at least 6 characters");
            return;
        }
        
        changePasswordMutation.mutate(password);
    };

    return (
        <div className="min-h-screen bg-linear-to-br from-gray-900 to-gray-800 flex flex-col justify-center items-center relative overflow-hidden group font-sans">
            {/* Animated Grid on Hover */}
            <div className="absolute inset-0 opacity-20 pointer-events-none"
                style={{ backgroundImage: 'radial-gradient(circle, #ffffff 1px, transparent 1px)', backgroundSize: '30px 30px' }}
            />
            {/* Decorative Glow */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-blue-600/20 rounded-full blur-[100px] pointer-events-none" />

            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6 }}
                className="w-full max-w-md relative z-10 px-4"
            >
                <div className="mb-8 flex justify-center">
                    <Logo theme="light" className="scale-125" />
                </div>

                <div className="bg-white/10 backdrop-blur-xl rounded-2xl shadow-2xl border border-white/10 p-8">
                    <div className="text-center mb-8">
                        <div className="w-16 h-16 bg-blue-500/20 rounded-full flex items-center justify-center mx-auto mb-4">
                            <FiCheck className="text-blue-400 text-2xl" />
                        </div>
                        <h2 className="text-2xl font-bold text-white mb-2">
                            Secure Your Account
                        </h2>
                        <p className="text-gray-400 text-sm">
                            For your safety, please replace the temporary password generated by your administrator with a secure permanent password.
                        </p>
                    </div>

                    <form onSubmit={handleSubmit} className="space-y-5">
                        <div className="space-y-5">
                            <div className="relative">
                                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-gray-400">
                                    <FiLock size={18} />
                                </div>
                                <input
                                    type="password"
                                    value={password}
                                    onChange={(e) => setPassword(e.target.value)}
                                    placeholder="Enter new password"
                                    required
                                    className="w-full pl-10 pr-4 py-3 bg-white/5 border border-white/10 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all"
                                />
                            </div>

                            <div className="relative">
                                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-gray-400">
                                    <FiLock size={18} />
                                </div>
                                <input
                                    type="password"
                                    value={confirmPassword}
                                    onChange={(e) => setConfirmPassword(e.target.value)}
                                    placeholder="Confirm new password"
                                    required
                                    className="w-full pl-10 pr-4 py-3 bg-white/5 border border-white/10 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all"
                                />
                            </div>
                        </div>

                        <button
                            type="submit"
                            disabled={changePasswordMutation.isPending}
                            className={`w-full py-3.5 px-4 font-bold rounded-xl shadow-lg transform transition-all duration-200 
                                ${changePasswordMutation.isPending 
                                  ? 'bg-blue-400 text-white opacity-70 cursor-not-allowed' 
                                  : 'bg-linear-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-400 text-white shadow-blue-500/20 hover:scale-[1.02] active:scale-[0.98]'
                                }`}
                        >
                            {changePasswordMutation.isPending ? 'Updating...' : 'Set Permanent Password'}
                        </button>
                    </form>
                </div>
                <p className="text-center text-gray-600 text-xs mt-8">
                    © 2025 VIRQA. All rights reserved.
                </p>
            </motion.div>
        </div>
    );
};

export default ForcePasswordChange;
